### DISCUSSION TITLE
Getting feedback instantly after setting values

### DISCUSSION THREAD

**Discussion by georgbachmann** [kodebach/hacs-idm-heatpump#204] [Q&A]
I am suuuuuuper new at creating my own button-cards, so it might easily just be me making stupid mistakes 😄 
So I have a row of three buttons, each to set a state for my heat pump. If I tap a button, the state changes immediately in my heat pump. If i reload the NavigatorPRO UI, it is set. If I am correct, this integration here updates it's state once every minute? I would think so, cause that's about as long (mostly shorter) as my buttons take to reflect the state.
Here's my first attempt of making a UI for the overall mode of my "Heizkreis A" (I only have one)
```
type: horizontal-stack
cards:
  - type: custom:button-card
    name: "Off"
    icon: mdi:power
    entity: sensor.luftwarmepumpe_betriebsart_heizkreis_a
    tap_action:
      action: call-service
      service: idm_heatpump.set_circuit_mode
      data:
        target: sensor.luftwarmepumpe_betriebsart_heizkreis_a
        value: "off"
        acknowledge_risk: true
    styles:
      card:
        - padding: 10px
      icon:
        - width: 20px
        - height: 20px
        - margin-bottom: 10px
    state:
      - value: "off"
        color: white
        styles:
          card:
            - background-color: var(--primary-color)
            - color: white
  - type: custom:button-card
    name: Eco
    icon: mdi:leaf
    entity: sensor.luftwarmepumpe_betriebsart_heizkreis_a
    tap_action:
      action: call-service
      service: idm_heatpump.set_circuit_mode
      data:
        target: sensor.luftwarmepumpe_betriebsart_heizkreis_a
        value: eco
        acknowledge_risk: true
    styles:
      card:
        - padding: 10px
      icon:
        - width: 20px
        - height: 20px
        - margin-bottom: 10px
    state:
      - value: eco
        color: white
        styles:
          card:
            - background-color: var(--primary-color)
            - color: white
  - type: custom:button-card
    name: Normal
    icon: mdi:heat-wave
    entity: sensor.luftwarmepumpe_betriebsart_heizkreis_a
    tap_action:
      action: call-service
      service: idm_heatpump.set_circuit_mode
      data:
        target: sensor.luftwarmepumpe_betriebsart_heizkreis_a
        value: normal
        acknowledge_risk: true
    styles:
      card:
        - padding: 10px
      icon:
        - width: 20px
        - height: 20px
        - margin-bottom: 10px
    state:
      - value: normal
        color: white
        styles:
          card:
            - background-color: var(--primary-color)
            - color: white
```

Basically everything works, just with a long delay!
So my question is: Am I doing something wrong here?
If not, then my suggestion would be to immediately update the entities state, after a call-service happened? So when I do
```
      action: call-service
      service: idm_heatpump.set_circuit_mode
      data:
        target: sensor.luftwarmepumpe_betriebsart_heizkreis_a
        value: normal
        acknowledge_risk: true
```
it would be nice it the state in HA for `sensor.luftwarmepumpe_betriebsart_heizkreis_a` would be set to normal immediately.
Same for target temperatures and so on (I am planning to set those as well for HA, so it would be nice it a +/- button press would be reflected right away)

I am a developer myself, but have NO IDEA about how home-assistant works under the hood. :-) 

But thank you very much for the whole integration! Very much appreciated!!!
