### DISCUSSION TITLE
Need Switches

### DISCUSSION THREAD

**Discussion by CheRRy1975** [kodebach/hacs-idm-heatpump#75] [Q&A] [answered]
Hello, I need a switch in the dashboard that can change the status of the heat pump (STANDBY = 0, AUTOMATIC = 1, AWAY = 2, HOLIDAY = 3, ONLY_HOT WATER = 4, ONLY_HEATING = 5).
But..... I just can not manage it.
I'm mainly interested in the two states "Holiday" & "Automatic". It would be great if the days on vacation could also be set (like in the app).

This also applies to the “Anforderung Warmwasserladung”. Theoretically, I would only have to pass the boolean value 1 here, since the IDM resets the status automatically, right? Unfortunately, a normal ON/OFF switch does not work here.

I hope someone can help me?

Many thanks

**Comment by kodebach** [comment, marked as answer]
The integration currently doesn't support setting those values. However, you can use the standard [Modbus](https://www.home-assistant.io/integrations/modbus/) integration (in addition to this integration) to achieve this. First set up the integration in `configuration.yaml`:

```yaml
modbus:
  - type: tcp
    name: heat_pump # or choose a different name
    host: IP_ADDRESS # set this just like you when setting up this integration
    port: 502
    sensors:
      - name: heatpump-operation-mode
        address: 1005
```

> [!IMPORTANT]
> The current version of HA requires that at least one sensor is defined. See also https://github.com/kodebach/hacs-idm-heatpump/discussions/75#discussioncomment-10214694

After a restart of Home Assistant, you can use the `modbus.write_register` service to send values to the heat pump.

```yaml
service: modbus.write_register
data:
  address: 1005
  slave: 1
  hub: heat_pump
  value: 0 # raw value for STANDBY like you described in your question
```

> [!CAUTION]
> This value (and most other writable values) is written to an EEPROM by the heat pump. These chips have limited number of write cycles (about 300 000), after which the chip may fail and need replacement. Make sure you know what you're doing and check (1) that you're only sending new values to the heat pump when necessary (i.e. value is different and needs update) and (2) you limit the number of automatic changes without user interaction.

---

>  It would be great if the days on vacation could also be set (like in the app).

I don't think setting the days for vacation status will be possible, since I don't see that exposed via Modbus anywhere. However, you may be able to use a Home Assistant Automation to automatically switch modes. To do that, it would probably best if you asked on the [Community Forum](https://community.home-assistant.io/) if you need help, since at that point it doesn't really matter whether your automation is toggling a switch for the heat pump or something else.

> This also applies to the “Anforderung Warmwasserladung”.

Same procedure as above, but with `address: 1712`. Alternatively, you can also configure a switch in the Modbus integration to directly toggle the state:

```yaml
modbus:
  - type: tcp
    # ... remaining config from above ...
    switches:
      - name: Switch1
        address: 1712
        write_type: holding
```

Not 100% sure if the status is automatically reset, but I guess it probably resets once the max. temperature is reached. However, I'm not certain the switch configured via the Modbus integration would update. You'd have to verify that.

> [!NOTE]
> This is actually one of the few (non-temperature) values that is not written to the EEPROM and can be written arbitrarily.

**Comment by CheRRy1975** [comment]
Thank you very much for your comprehensive answer! :)

Then I'll get to work... with all the caution required (by you).

**Comment by HoBPirE** [comment]
After spending quite a while to use the modbus.write_register service, I still get following error:

![image](https://github.com/user-attachments/assets/4d7ccc23-a388-4c62-86a6-7020cd5f06de)

Any clue?

modbus is initiated in configuration.yaml:

```yaml
modbus:
  - type: tcp
    name: heat_pump # or choose a different name
    host: 192.168.178.61 # set this just like you when setting up this integration
    port: 502
    
    delay: 0
    message_wait_milliseconds: 30
    timeout: 5
```

**Reply by HoBPirE** [reply]
Found the solution. With current HA version, at least one entity needs to be defined. Now it is working. Example:

```yaml
modbus:
  - type: tcp
    name: heatpump # or choose a different name
    host: 192.168.178.61 # set this just like you when setting up this integration
    port: 502
    delay: 0
    message_wait_milliseconds: 30
    timeout: 5
    sensors:
      - name: heatpump-operation-mode
        address: 1005
```

**Reply by kodebach** [reply]
Good to know, I updated the answer above

**Comment by daemonenstall** [comment]
I don't know since when, but switches can be directly defined beneath the configuration of the hub.
```
  - name: idm
    type: tcp
    host: 192.168.1.105
    port: 502
    delay: 0
    message_wait_milliseconds: 30
    timeout: 1
    switches:
      - name: Warmwasserladung
        address: 1713
        write_type: coil
        command_on: 1
        command_off: 0
        verify:
          address: 1112
          delay: 0
          input_type: holding
          state_on: 1
          state_off: 0
```
