### DISCUSSION TITLE
Problems writing

### DISCUSSION THREAD

**Discussion by KVS62** [kodebach/hacs-idm-heatpump#77] [Q&A] [answered]
I previously used a modified version of SimowN's set-up to write the solar production and surplus to the heat pump (Navigator 2.0). Last week I installed the HACS implementation, but I have not been able to get this to write the values to the heat pump. Values are being read.

My config.yaml looks as follows:

```yaml
 # Loads default set of integrations. Do not remove.
default_config:

# Text to speech
tts:
  - platform: google_translate
  
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

template:
  - sensor:
      - name: "PV aktuelle Produktion"
        unique_id: "power_solar_production"
        unit_of_measurement: "kW"
        state: >
          {% if has_value('sensor.myenergi_harvi_10338601_power_ct_generation') == False %}
            {{ 0.0 }}
          {% else %}
            {{ (states('sensor.myenergi_harvi_10338601_power_ct_generation')|float / 1000|float ) }}
          {% endif %}
        state_class: measurement
        device_class: power
        icon: mdi:solar-power
      - name: "WP aktueller PV Überschuss"
        unique_id: "power_solar_surplus"
        unit_of_measurement: "kW"
        state: >
          {% if has_value('sensor.myenergi_harvi_10338601_power_ct_generation') == False or has_value('sensor.p1_net_electricity_point') == False %}
            {{ 0.0 }}
          {% elif states('sensor.p1_net_electricity_point')|float > 0 %}
            {{ 0.0 }}
          {% else %}
            {{ (states('sensor.p1_net_electricity_point')|float / -1000|float ) }}
          {% endif %}
        state_class: measurement
        device_class: power
        icon: mdi:solar-power
```

and the script as follows:

```yaml
idm_update_pv_values:
  alias: Update Photovoltaik values to IDM Headpump
  sequence:
  - service: idm_heatpump.set_power
    data:
      target: sensor.idm_heat_pump_aktueller_pv_uberschuss
      value: >
        {{ states("sensor.power_solar_surplus") }}
  - service: idm_heatpump.set_power
    data:
      target: sensor.idm_heat_pump_aktueller_pv_produktion
      value: >
        {{ states("sensor.power_solar_production") }}
  mode: single
```

Is there any additional configuration action that needs to be taken to be able to write the values?

Any help would be greatly appreciated.

**Comment by kodebach** [comment]
I think you need to use `{{ states("sensor.power_solar_surplus") | float }}` and `{{ states("sensor.power_solar_production") | float }}` in the script. If that doesn't work, please check whether there are any relevant messages in the Home Assistant logs (Settings -> System -> Logs)

---

FYI: To get proper formatting for the config you should use

````markdown
[normal text]
```yaml
[CONFIG GOES HERE]
```
[more text]
````

because this <code>\` ... \`</code> only works for a single line.

**Reply by KVS62** [reply]
Thanks for your quick reply. Very much appreciated. I did the change that you suggested, but without any success. 

Then I discovered something strange in the entities: PV aktuelle Produktion ase well as the one for surplus still had the old sensor from when I used the adapted SimowN's configs. I went in and edited this to the correct ones (e.g. sensor.power_solar_production)

This solved finally solved the problem (being a beginner is frustrating).

It seems though that the solar production is not updated all the time. 

Is this related to the condition statement that I have in the automation file?

`condition:`
  `- '{{ not is_state(''sensor.power_solar_surplus'',''sensor.idm_heat_pump_aktueller_pv_uberschuss'')`
    `}}'`

**Reply by kodebach** [reply, marked as answer]
Not sure, what you wanted to achieve with the condition. I'm not a heavy user of the templating in Home Assistant, so I may be wrong here, but: `is_state(A, B)` seems to check whether the state of sensor `A` is the value `B`. So in your case it compares against the literal value `sensor.idm_heat_pump_aktueller_pv_uberschuss`. I don't think that is what you wanted.

If this is just an attempt at limiting the number of values sent to the heat pump, then I don't think that's necessary. The "PV-Überschuss" value isn't stored persistently, so AFAIK there is no limit on how often you can write it.

If you still want the condition, using the Automation UI I get (`states` in the second argument makes Home Assistant actually read the current state of the sensor):

```yaml
condition:
  - condition: template
    value_template: "{{ not is_state('sensor.power_solar_surplus', states('sensor.idm_heat_pump_aktueller_pv_uberschuss')) }}"
```
